platform :ios, '11.0'
use_frameworks!
source 'https://github.com/LivePersonInc/iOSPodSpecs.git' #LiveEngage Pod Repository

target 'SampleApp' do
  #LPMessagingSDK Includes: LPAMS.framework, LPInfra.framework, LPMessagingSDK.framework and  LPMessagingSDKModels.bundle
  pod 'LPMessagingSDK','5.2.1.1306-Swift-5.3-Beta-4'
end
