      platform :ios, '11.0'
      use_frameworks!
      source 'https://github.com/LivePersonInc/iOSPodSpecs.git' #LiveEngage Pod Repository

      target 'SampleApp' do
        #LPMessagingSDK Includes: LPAMS.framework, LPInfra.framework, LPMessagingSDK.framework and  LPMessagingSDKModels.bundle
        pod 'LPMessagingSDK','6.1.0.747'
      end
